version: 2

build:
    image: latest

conda:
    environment: requirements/ci/geovista.yml

sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: false

python:
    install: 
        - method: setuptools
          path: .

formats:
    - htmlzip
    - pdf
