[build-system]
# Defined by PEP 518
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "setuptools_scm_git_archive",
    "wheel"
]
# Defined by PEP 517
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 88
target-version = ["py38", "py39"]
include = '\.pyi?$'


[tool.isort]
force_sort_within_sections = "True"
known_first_party = "geovista"
line_length = 88
profile = "black"
skip_gitignore = "True"
verbose = "False"


[tool.setuptools_scm]
write_to = "lib/geovista/_version.py"
local_scheme = "dirty-tag"
